from sqlalchemy import Boolean, Column, DateTime, ForeignKey, Numeric, String, Text

from app.models.base import Base, JSONType, TimestampMixin, UUIDType


class GoogleRecommendation(TimestampMixin, Base):
    """SOP-driven optimization recommendation for Google Ads.

    Generated by detectors in app/services/google_recommendations/detectors/.
    Enriched by Claude, surfaced via /google/recommendations, applied via
    google_actions.py behind a custom per-type warning. All apply events
    append an immutable action_logs row.
    """

    __tablename__ = "google_recommendations"

    rec_type = Column(String(80), nullable=False, index=True)
    severity = Column(String(16), nullable=False, index=True)  # critical | warning | info
    status = Column(
        String(20),
        nullable=False,
        default="pending",
        index=True,
    )  # pending | applied | dismissed | expired | failed | superseded

    account_id = Column(
        UUIDType,
        ForeignKey("ad_accounts.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    campaign_id = Column(
        UUIDType,
        ForeignKey("campaigns.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    ad_group_id = Column(
        UUIDType,
        ForeignKey("ad_sets.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    ad_id = Column(
        UUIDType,
        ForeignKey("ads.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    asset_group_id = Column(
        UUIDType,
        ForeignKey("google_asset_groups.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )

    entity_level = Column(String(20), nullable=False)  # account|campaign|ad_group|asset_group|ad
    campaign_type = Column(String(20), nullable=True, index=True)  # SEARCH|PMAX|DEMAND_GEN|PORTFOLIO

    title = Column(String(300), nullable=False)
    detector_finding = Column(JSONType, nullable=False)
    metrics_snapshot = Column(JSONType, nullable=False)
    ai_reasoning = Column(Text, nullable=True)
    ai_confidence = Column(Numeric(3, 2), nullable=True)
    suggested_action = Column(JSONType, nullable=False)
    auto_applicable = Column(Boolean, nullable=False)
    warning_text = Column(Text, nullable=False)
    sop_reference = Column(String(40), nullable=True)

    dedup_key = Column(String(180), nullable=False, index=True)
    expires_at = Column(DateTime(timezone=True), nullable=False)

    applied_at = Column(DateTime(timezone=True), nullable=True)
    applied_by = Column(UUIDType, nullable=True)
    dismissed_at = Column(DateTime(timezone=True), nullable=True)
    dismissed_by = Column(UUIDType, nullable=True)
    dismiss_reason = Column(Text, nullable=True)

    action_log_id = Column(
        UUIDType,
        ForeignKey("action_logs.id", ondelete="SET NULL"),
        nullable=True,
    )
    source_task_id = Column(String(80), nullable=True)
